name: PickleCraft
main: net.picklecraft.PickleCraftPlugin
author: Pickle
version: 1.8.5
description: Adds various usefull things.
softdepend: [WorldEdit, PermissionsEx, LogBlock]
commands:
    ignore:
        permission: PickleCraft.ignore
        description: Ignores the player, "-r" is an optional flag to remove player from ignoreList.
        usage: /ignore <-r> [player]
    ignoreall:
        permission: PickleCraft.ignore
        description: Blocks all chat except a select few.
        usage: /ignoreall
    ignoreList:
        description: Displays your ignore list.
        usage: /ignorelist
    pony:
        description: Fluttershy told me to do it!
        usage:
    tpac:
        permission: PickleCraft.teleport.coord
        description: Teleport to specfic coordinate, do be careful.
        usage: /tpac [x,y,z] ; y is optional.
    tpa:
        permission: PickleCraft.teleport
        description: Sends a player a request to teleport you, <unless you spefic a second player.>
        usage: /tpa [player] <target>
    tpahere:
        permission: PickleCraft.teleport.here
        description: Request a player to teleport to you.
        usage: /tpahere [player]
    tpdeny:
        description: Denies teleport request
        usage:
    tpaccept:
        usage:
    tpareturn:
        permission: PickleCraft.teleport.return
        description: Returns to last location before a teleport.
        usage: /tpareturn
    pw:
        permission: PickleCraft.privatewarps
        description: Set,list,or removes private warps.
        usage: /pw [SET,REMOVE,LIST] [name]
    picklecraft:
        description: Help command
        usage: 
permissions:
 PickleCraft.*:
   description: Full access.
   children:
     PickleCraft.ignore: true
     PickleCraft.teleport: true
     PickleCraft.teleport.here: true
     PickleCraft.teleport.coord: true
     PickleCraft.teleport.dualplayers: true
     PickleCraft.teleport.return: true
     PickleCraft.timber: true
    
 PickleCraft.ignore:
   description: Allows use of ignore commands.
   default: true
 PickleCraft.ignore.cantbeignored:
   description: can't be ignored.
   default: op
 PickleCraft.teleport.accept:
   description: Allows use of /tpaccept
   default: true
 PickleCraft.teleport:
   description: Allows use of /tpa [player]
   default: true
 PickleCraft.teleport.dualplayers:
   description: Allows use of /tpa [player] [player]
   default: op
 PickleCraft.teleport.coord:
   description: Allows use of /tpac
   default: true
 PickleCraft.teleport.here:
   description: Allows use of /tpahere
   default: true
 PickleCraft.teleport.return:
   description: Allows use of /tpareturn
   default: true
 PickleCraft.reload:
   description:
   default: op
 PickleCraft.signrank.build:
   description: Allows use of SignRank Sign Placement
   default: op
 PickleCraft.counter.build:
   description: Allows use of Counter Sign Placement
   default: true
 PickleCraft.timber.cut:
   description: Allows mass log cutting.
   default: true
 PickleCraft.timber.cut.jungle:
   description: Allows mass log cutting.
   default: true
 PickleCraft.privatewarps:
   description: allows privatewarps.
   default: true