name: PickleCraft
main: net.picklecodes.PickleCraftPlugin
author: Pickle
version: 1.6.5
description: This plugin simply adds a command to ignore annoying users, now with teleport commands.
softdepend: [WorldEdit, PermissionsEx]
commands:
    ignore:
        permission: IgnoreCraft.ignore
        description: Ignores the player, "-r" is an optional flag to remove player from ignoreList.
        usage: /ignore <-r> [player]
    ignoreall:
        permission: IgnoreCraft.ignore
        description: Blocks all chat except a select few.
        usage: /ignoreall
    ignoreList:
        description: Displays your ignore list.
        usage: /ignorelist
    pony:
        description: Fluttershy told me to do it!
        usage:
    tpac:
        permission: IgnoreCraft.teleport.coord
        description: Teleport to specfic coordinate, do be careful.
        usage: /tpac [x,y,z] ; y is optional.
    tpa:
        permission: IgnoreCraft.teleport
        description: Sends a player a request to teleport you, <unless you spefic a second player.>
        usage: /tpa [player] <target>
    tpahere:
        permission: IgnoreCraft.teleport.here
        description: Request a player to teleport to you.
        usage: /tpahere [player]
    tpdeny:
        description: Denies teleport request
        usage:
    tpaccept:
        usage:
    tpareturn:
        permission: IgnoreCraft.teleport.return
        description: Returns to last location before a teleport.
        usage: /tpareturn
    picklecraft:
        description: Help command
        usage:
    pcreload:
        permission: PickleCraft.pcreload
        description: 
        usage: 
    pcload:
        permission: PickleCraft.pcreload
        description: 
        usage: 
    pcunload:
        permission: PickleCraft.pcreload
        description: 
        usage: 
permissions:
 IgnoreCraft.*:
   description: Full access.
   children:
     IgnoreCraft.ignore: true
     IgnoreCraft.teleport: true
     IgnoreCraft.teleport.here: true
     IgnoreCraft.teleport.coord: true
     IgnoreCraft.teleport.dualplayers: true
     IgnoreCraft.teleport.return: true
    
 IgnoreCraft.ignore:
   description: Allows use of ignore commands.
   default: true
 IgnoreCraft.ignore.cantbeignored:
   description: can't be ignored.
   default: op
 IgnoreCraft.teleport:
   description: Allows use of /tpa [player]
   default: true
 IgnoreCraft.teleport.dualplayers:
   description: Allows use of /tpa [player] [player]
   default: op
 IgnoreCraft.teleport.coord:
   description: Allows use of /tpac
   default: true
 IgnoreCraft.teleport.here:
   description: Allows use of /tpahere
   default: true
 IgnoreCraft.teleport.return:
   description: Allows use of /tpareturn
   default: true
 PickleCraft.signrank.build:
   description: Allows use of SignRank Sign Placement
   default: op
 PickleCraft.counter.build:
   description: Allows use of Counter Sign Placement
   default: true
 PickleCraft.reload
   description: 
   default: op
 PickleCraft.timber.cut:
   description: Allows mass log cutting.
   default: true
     